server:
  port: 8085
  
spring:
  application:    name: circuit-sentinel  cloud:    # 断路器 Sentinel相关配置
    sentinel:
      #filter:
        # 是否支持对Spring MVC的限流（注意：这个一般不配置）      #  enabled: false
      transport:
        # 控制台地址
        dashboard: 192.168.83.143:8080
        # 指定和控制台通信的IP，不建议配置（如果不指定会自动选择一个）（注意：这个IP是当前机器的）
        #client-ip: 127.0.0.1
        # 指定和控制台通信的端口（如果不指定会自动选择一个）（注意：这个端口是绑定在当前机器上的）
        port: 8719
        # Sentinel和Sentinel Dashboard的心跳时间（默认 10000）
        #heartbeat-interval-ms: 1000
        
# 监控相关配置
management:
  endpoints:
    web:
      # 暴露所有监控接口
      exposure:
        include: '*'                  