server:
  port: 8081
spring:
  main:
    # 解决多Feign同名的错误    allow-bean-definition-overriding: true
  application:
    name: user-web
  # JSON相关配置
  jackson:
    locale: zh_CN
    default-property-inclusion: non-null
  # Spring Cloud 相关配置  
  cloud:
    # Nacos相关配置
    nacos:
      discovery:
        enabled: true
        # 是否注册当前服务
        register-enabled: false
        # 需要调用哪个namespace的服务（注意：这个配置的是id而不是名称）
        namespace: 3899f87a-1741-4ab9-bca9-64352a882879
        # 需要调用哪个集群的服务
        cluster-name: SZ
        server-addr: 192.168.83.143:8848  
    # 断路器 Sentinel相关配置
    sentinel:      transport:
        # 控制台地址        dashboard: 192.168.83.143:8080
# 配置Ribbon饿加载（默认是代码执行到了才加载，所以第一次可能会有点慢），这样可以加快首次执行效率
ribbon:
  okhttp:    enabled: true
  eager-load:
    # 开启饿加载（推荐生产使用）
    enabled: true
    # 指定Service名称（多个用逗号开）
    clients: user-service    
    
# 配置Feign的日志级别（注意：一定要是debug，还有就是要定义Feign本身的日志级别（具体看springcloud_test/client-feign/README.md说明），否则无法生效）
logging:
  level:
    com.firecode.springcloud_test.alibaba.user.feign.service.UserServiceClient: debug
    
# Feign相关配置    
feign:
  # 开启Feign整合Sentinel（使用方法：开启后在控制台为Feign调用的接口配置限流即可）（注意：不推荐使用，写回调太麻烦，再一个限流还是在服务端自己做比较好）
  sentinel:
    enabled: true
  okhttp:
    # 开启使用okhttp发起请求（使用连接池优化性能），而不是默认的UrlConnection
    enabled: true
  httpclient:
    # 关闭HttpClient发起请求，因为我使用okhttp发起请求
    enabled: false
    # 连接超时时间
    connection-timeout: 5000
    # Feign最大连接数
    max-connections: 200
    # 单个路径最大连接数
    max-connections-per-route:  50
  client:
    config:
      # 服务名称（下面是Feign的日志级别，注意：还要配置 logging:level:com.firecode.springcloud_alibaba.user.api.service.UserService=debug否则服务生效）
      #user-service: 
      #  logger-level: full   
      # 全局配置（所有服务都生效）
      default:
        logger-level: full
        
# 监控相关配置
management:  endpoints:    web:
      # 暴露所有监控接口      exposure:        include: '*'